spring:
  application:
    name: wjh-ai-agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://pgm-2ze6n6epn1a79w0jto.pg.rds.aliyuncs.com:5432/wjh_ai_agent
    username: My_user_wjh1
    password: My_user_wjh1
  vectorstore:
    pgvector:
      initialize-schema: true
      index-type: HNSW
      dimensions: 1536
      distance-type: COSINE_DISTANCE
      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

server:
  port: 8100
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wjh.wjhaiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org.springframework.ai: debug

#searchAPI
search-api:
  api-key: giAEP3wXdD5noa17Qhpdp9sc
